mac_task:
  only_if: $CIRRUS_BRANCH == 'master'
  timeout_in: 10m
  osx_instance:
    image: mojave-xcode
  brew_installs_script:
    - brew install yarn
    - brew install rpm
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[9045ce6b930edefbd4c14d388a3e963cf6bcc938815aebcb0b331800bd0c3f76587533ce9207e7989138a7ed9afd7159]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[3fd7909c3b2e089d38da979bb3420cd7d6c68fc757129aef403f5f1f866183459afc5938d2fcb6403d57ba53543345ff]
    CSC_IDENTITY_AUTO_DISCOVERY: false
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  package_and_publish_mac_script: yarn run release:mac
  package_and_publish_win_script: yarn run release:win

linux_task:
  only_if: $CIRRUS_BRANCH == 'master'
  timeout_in: 10m
  container:
    image: node:latest
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[9045ce6b930edefbd4c14d388a3e963cf6bcc938815aebcb0b331800bd0c3f76587533ce9207e7989138a7ed9afd7159]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[3fd7909c3b2e089d38da979bb3420cd7d6c68fc757129aef403f5f1f866183459afc5938d2fcb6403d57ba53543345ff]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  package_and_publish_linux_script: yarn run release:linux
